version: '3'

services:
  docker-postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
      - POSTGRES_DB=userregistration
    volumes:
    - "C:/Users/My Dell/Desktop/PostgreSQLDb:/var/lib/postgresql/data"