version: '3'

services:
  docker-postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
      - POSTGRES_DB=userregistration
    volumes:
    - "C:/Users/Dmytro_Kononenko1/Desktop/PostgreSQLDb:/var/lib/postgresql/data"
  maildev:
    image: maildev/maildev
    ports:
      - 1080:80
      - 1025:25
  springboot-docker-app:
    image: my-spring-app-v2
    depends_on:
      - docker-postgres
      - maildev
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=docker-postgres
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=userregistration
      - DATABASE_PORT=5432